### PR TITLE
added battery level plugin, Tested on Mac, test needed for Window and Linux

### PR DESCRIPTION
**Pull request by Or3stis**
I made a battery level plugin 🎉 

It has been tested on mac os. Here is the screenshot. I added the battery icon (🔋)  to separate it from the other values. 
screen shot 2016-08-27 at 20 00 24

I have added dummy code for the other platforms. For windows and linux systems it renders a 😞 
screen shot 2016-08-27 at 21 06 59

In order to show the battery level in Windows and Linux, we only need to add the system command for those systems in the else..if statements inside.

I don't own Windows or Linux, so can't test them.

### CODE REVIEW

**Comment by timneutkens** [comment]
Does electron support https://github.com/pstadler/battery.js? Otherwise it might be good to use that for cross platform support and all 👍

**Comment by Or3stis** [comment]
That is a great idea!! I keep forgetting that we can use Web Apis for Electron apps. I will look into that and make a new PR once it is finished.

**Comment by timneutkens** [comment]
Great 👍

**Comment by Or3stis** [comment]
I am having some trouble displaying information from the client and rendering it with react, like the `window.navigator.getBattery()` as it is.

It is resulting in quite a rewrite of the code, so I was thinking making hyperline more "api-like".

We could have one module for displaying client side information, such as Web apis or window width/height, et cetera..
And another module for server side information, that would display system information such as CPU, hostnames and the like.
Using those modules we can a have configuration file to choose what is going to be displayed in the status bar.
I would be much cleaner in the long run.

What do you think?

**Comment by NickTikhonov** [comment]
@Or3stis - thanks for proposing the battery plugin :) We're definitely intending to make hyperline more modular. The two things to consider are how easy it is to add new plugins to the system, and how frictionless the process of installing and using hyperline is. I think the best approach right now is to keep all plugins in the main repo and provide a means of configuring the visibility/order/color of every component to the user. This favours ease of use by removing steps from initial installation and configuration. Let me know if you have any thoughts or opinions on the matter and thanks for contributing! 🚀

**Comment by Or3stis** [comment]
@NickTikhonov - I agree 😄  

Is anyone working on a way of configuring hyperline?

**Comment by timneutkens** [comment]
@Or3stis me and Nick are talking about it on [zeit.chat](http://zeit.chat)

**Comment by NickTikhonov** [comment]
@Or3stis - I merged the battery plugin added in #28, which is cross-platform and delegates to [another module](https://github.com/sebhildebrandt/systeminformation) for the information we need. Closing this for now  :) Please feel free to contribute to other aspects of the project - perhaps the other stuff we talked about in this PR :D

**Pull request closed without merging**
