### PR TITLE
Fix content positioning on narrow windows/tabs

### PR DESCRIPTION
**Pull request by davegomez**
positioning

### CODE REVIEW

**Comment by MaxBittker** [comment]
👍  although my preference would be to use a breakpoint to drop something besides network load

**Comment by davegomez** [comment]
We are not dropping anything @MaxBittker, they are being displayed just that they doesn't fit in the space, is like overflow without an scroll bar.

**Comment by timneutkens** [comment]
I'm going to merge this for now, will try something else later on.

**Comment by MaxBittker** [comment]
@davegomez I understand, but considering that we have the responsive design power of css, it would be nice to drop ui elements in a different order. this is an improvement though!

**Comment by davegomez** [comment]
@MaxBittker can you explain your idea in graphical way, I think I don't understand what you propose

**Comment by MaxBittker** [comment]
@davegomez 
https://jsfiddle.net/st9x5z33/
perhaps something like this? or using media query breakpoints to make the transition more discrete.

**Comment by timneutkens** [comment]
@MaxBittker could you create a new issue for this? Then we won't forget to fix it later on 😉 Many thanks for your input, seems like a smart idea to hide an element. Might be best to just `display: none` them though.

**Comment by davegomez** [comment]
That's exactly what it does @MaxBittker but it just stop shrinking the elements once they reach their minimum width to avoid distortion the elements

**Comment by MaxBittker** [comment]
@timneutkens 😄  you should make a  npm release so we can pull these sweet improvements

**Comment by timneutkens** [comment]
I know right. Will contact Nick.

**Comment by davegomez** [comment]
I forgot I'm using the development version and assume everyone were enjoying the latest additions.

**Pull request merged**
