### PR TITLE
Configure ESLint with Idiomatic

### PR DESCRIPTION
**Pull request by JerryLopez**
@timneutkens @NickTikhonov 

I've got ESLint configured along with [Idiomatic](https://github.com/rwaldron/idiomatic.js/). I corrected all the code style errors as well, but have 6 errors remaining that idk how to correct or what the issue is. 

The errors are:

- LINE_COLOR is defined but never used [src/index.js:L13](https://github.com/JerryLopez/hyperterm-hyperline/blob/7d364c3f95b49aa78ea64b5f418642269c9f31b8/src/index.js#L13)
- HOSTNAME_COLOR is defined but never used [src/index.js:L14](https://github.com/JerryLopez/hyperterm-hyperline/blob/7d364c3f95b49aa78ea64b5f418642269c9f31b8/src/index.js#L14)
- MEMORY_INFO_COLOR is defined but never used [src/index.js:L15](https://github.com/JerryLopez/hyperterm-hyperline/blob/7d364c3f95b49aa78ea64b5f418642269c9f31b8/src/index.js#L15)
- UPTIME_INFO_COLOR is defined but never used [src/index.js:L16](https://github.com/JerryLopez/hyperterm-hyperline/blob/7d364c3f95b49aa78ea64b5f418642269c9f31b8/src/index.js#L16)
- Hyperline is defined but never used [src/index.js:L26](https://github.com/JerryLopez/hyperterm-hyperline/blob/7d364c3f95b49aa78ea64b5f418642269c9f31b8/src/index.js#L26)
- Component is defined but never used [src/index.js:L42](https://github.com/JerryLopez/hyperterm-hyperline/blob/7d364c3f95b49aa78ea64b5f418642269c9f31b8/src/index.js#L42)

Let me know what you guys think! 😁

### CODE REVIEW

**Comment by timneutkens** [comment]
@JerryLopez Try to merge the current master branch. It will fix:
>LINE_COLOR is defined but never used src/index.js:L13
HOSTNAME_COLOR is defined but never used src/index.js:L14
MEMORY_INFO_COLOR is defined but never used src/index.js:L15
UPTIME_INFO_COLOR is defined but never used src/index.js:L16

The others are used using jsx `<Hyperterm>` and `<Component>` eslint is probably not configured to support jsx. [Eslint-plugin-react](https://www.npmjs.com/package/eslint-plugin-react) shows how to enable jsx. You probably won't have to install that module though. Just enable it using
```
  "parserOptions": {
    "ecmaFeatures": {
      "jsx": true
    }
  }
```
in .eslintrc

**Comment by NickTikhonov** [comment]
@JerryLopez this is awesome - let me know when you think this is ready and I will set up CI to run the linter :D

**Comment by timneutkens** [comment]
@NickTikhonov Looking at it right now for @JerryLopez. [Come on slack](http://zeit.chat)! 👍

**Comment by NickTikhonov** [comment]
There was an issue where the CPU plugin stopped working - fixed it [here](https://github.com/NickTikhonov/hyperterm-hyperline/commit/a2e5393f1d0161494a7efe3e7f9eb0cbf7bf8a65) :)

**Comment by timneutkens** [comment]
You can merge it now 🎉

**Pull request merged**
