### PR TITLE
Remove canvas, move to plain html.

### LINKED ISSUE #6: Conflicts with Hyperborder
Hey!

Not sure what repo to report this in but this plugin seems to conflict with [Hyperborder](https://github.com/webmatze/hyperborder)

Screenshot attached:
screen shot 2016-07-20 at 3 26 51 pm

### PR DESCRIPTION
**Pull request by timneutkens**
I feel like I killed your baby @NickTikhonov. But it's in favour of a bigger cause 😉 There are virtually no speed implications. I kinda rewrote the whole codebase to a smaller footprint. Will look into moving this to React components tomorrow (well.. today actually, after I've slept 👍)

It includes @JerryLopez his work. So if you're going to merge this please merge #9 first.

Side note: this also fixes #6 🚀

### CODE REVIEW

**Comment by timneutkens** [comment]
Almost done porting to React. Hold off on merging this 👍

**Comment by NickTikhonov** [comment]
@timneutkens this is smart - I much prefer rendering to the DOM instead of Canvas. The initial implementation is largely a hack. Looking forward to merging this in! 👍

**Comment by timneutkens** [comment]
Cool that you're on board with it haha, wasn't sure if you would be.. literally refactored almost everything hahaha. React is almost done. Working on porting the cpu module now. After that I'll push.

**Comment by NickTikhonov** [comment]
@timneutkens 🔥 🔥 🔥

**Comment by timneutkens** [comment]
Let the review begin 👍

**Comment by NickTikhonov** [comment]
Good work @timneutkens - made two minor changes, everything else looks great 👍 Would be interesting to consider whether or not we can make use of Redux instead of storing state in the info components. Thoughts?

**Pull request merged**
