### PR TITLE
Use battery status provided by electron

### PR DESCRIPTION
**Pull request by timneutkens**

### CODE REVIEW

**Comment by davegomez** [comment]
There is a problem with this approach as well as using systeminformation library to get the battery percent, both use the battery's maxcapacity and currentcapacity values to calculate the current load percent but these values are not always the same when the battery is at full charge.

This is because the battery will have some degradation with time and the current capacity will be lower than the max capacity, showing a misleading battery percent as you can see in the screenshot.

battery

I'm working on a fix to this issue for systeminformation so maybe we can use it later.

Opinions, suggestions?

**Comment by timneutkens** [comment]
I would stick with the provided battery info from electron. It might just be that the batterymanager did not trigger the change event. @NickTikhonov what do you think?

**Comment by davegomez** [comment]
Forget about my previos comment, the Battery Status API doesn't have that issue.

**Comment by timneutkens** [comment]
That's nice 👍 😄

**Pull request merged**
